services:
  db:
    image: mysql:8.0.31
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./web:/var/golang/web
    depends_on:
      - db
volumes:
  db-store:
