services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8000:8000
    command: go run /var/golang/web/main.go
    restart: on-failure
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./web:/var/golang/web
      - ./web/go.mod:/var/golang/web/go.mod
