services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: ./docker/web
    ports:
      - 8000:8000
